---
# envars
editor: vim
browser: firefox
term: rxvt
text:
  font: DejaVu Sans Mono
  size: 18

# time
time_zone: US/Mountain

# locale
locale: en_US.UTF-8 UTF-8
lang: en_US.UTF-8

# base packages
pkgs:
  - base-devel
  - alsa-utils
  - dialog
  - git
  - htop
  - linux-headers
  - lsof
  - mlocate
  - nmap
  - rsync
  - speedtest-cli
  - sudo
  - tcpdump
  - vim
  - wget
  - wpa_supplicant
  - zsh

vagrant_plugins:
  # - vagrant-hostsupdater
  # - vagrant-share
  # - vagrant-vbguest
