---
language: c

before_install:
  - sudo add-apt-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get -y -qq install ansible

install:
  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - ansible-galaxy install tomc603.ntp

script:
  # Check syntax
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run test playbook
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo

  # Check subsequent runs are idempotent
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotent Check: OK'; exit 0)
    || (echo 'Idempotent Check: FAIL'; exit 1)
