---
- name: Set timezone to {{time_reg}} {{time_zone}}
  file:
    src=/usr/share/zoneinfo/{{time_reg}}/{{time_zone}}
    dest=/etc/localtime
    owner=root
    group=root
    state=link
  tags: [ "time" ]

- name: Install ntp
  package:
    name: ntp
    state: present
  tags: [ "time" ]

- name: Copy the ntp.conf template file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
   - restart ntpd
  tags: [ "time" ]
