- name: install mutt and deps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mutt
    - msmtp
    - gnupg
  tags:
    - email
    - mutt

- name: install mutt deps from aur
  yay:
    name: isync
    user: "{{ user.name }}"
  tags:
    - email
    - mutt

- name: Download configs from github
  become: false
  git:
    repo: https://github.com/ork/mutt-office365.git
    dest: "/home/{{ user.name }}/.mutt"
    version: master
    update: no
  tags:
    - email
    - mutt

- name: Generate ~/.mutt/user
  template:
    src: user.j2
    dest: "/home/{{ user.name }}/.mutt/user"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  tags:
    - email
    - mutt
