- name: install mutt and deps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mutt
    - msmtp
    - gnupg
  tags:
    - email
    - mutt

- name: install mutt deps from aur
  yaourt:
    name: isync
    user: "{{ ansible_user }}"
  tags:
    - email
    - mutt

- name: Download configs from github
  become: false
  git:
    repo: https://github.com/ork/mutt-office365.git
    dest: "/home/{{ ansible_user }}/.mutt"
    version: master
    update: no
  tags:
    - email
    - mutt

- name: Generate ~/.mutt/user
  template:
    src: user.j2
    dest: "/home/{{ ansible_user }}/.mutt/user"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  tags:
    - email
    - mutt
