---
- name: Allow {{ ansible_user }} to have passwordless sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^{{ ansible_user }}' line='{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'"
  tags:
    - setup
