---
- name: Set hostname
  hostname: name={{ inventory_hostname }}
  tags: [ 'hostname' ]

- name: Generate /etc/hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
  tags: [ 'hostname' ]
