---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
    - "./secrets/{{ inventory_hostname }}.yml"

  roles:
    - hostname
    - mkinitcpio
    - locale
    - time
    - pkgs
    - git
    - yaourt
    # - user
    # - authorized_keys
    # - sudoers
    # - docker
    # - gpg
    # - mysql
    # - psql
    # - ruby
    # - slim
    # - vagrant
    - ansible
    - browser
    - chef
    - conky
    - hosts
    - i3
    - python
    - ssh
    - vim
    - virtualbox
    - vpn
    - zsh

  tasks:

    - name: install vagrant
      package:
        name: vagrant
        state: present
      tags: [ 'vagrant' ]

    - name: install chat apps from aur
      yaourt:
        name: "{{ item }}"
        user: "{{ ansible_user }}"
      with_items:
        - bluejeans
        - hipchat
      tags: [ 'chat' ]

    - name: install evolution email client
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - evolution
        - evolution-ews
        - gnome-keyring
      tags: [ 'email' ]

    - name: install terraform from aur
      yaourt:
        name: terraform
        user: "{{ ansible_user }}"
      tags: [ 'terraform' ]

    - name: install libreoffice
      package:
        name: libreoffice-fresh
        state: present
      tags: [ 'libreoffice' ]

    - name: Install transmission
      package:
        name: transmission-gtk
        state: present
      tags: [ 'bittorrent' ]
