---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
    - "./secrets/{{ inventory_hostname }}.yml"

  roles:
    - hostname
    - mkinitcpio
    - locale
    - time
    - pkgs
    - git
    - yaourt
    # - user
    # - authorized_keys
    # - sudoers
    # - docker
    # - gpg
    # - mysql
    # - psql
    # - ruby
    # - slim
    # - vagrant
    - ansible
    - browser
    - chef
    - conky
    - hosts
    - i3
    - python
    - ssh
    - vim
    - virtualbox
    - vpn
    - zsh

  tasks:

    - name: install vagrant
      package:
        name: vagrant
        state: present
      tags: [ 'vagrant' ]

    - name: install chat apps from aur
      yaourt:
        name: "{{ item }}"
        user: "{{ ansible_user }}"
      with_items:
        - bluejeans
        - hipchat
      tags: [ 'chat' ]

    - name: install evolution email client
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - evolution
        - evolution-ews
        - gnome-keyring
      tags: [ 'email' ]

    - name: install terraform from aur
      yaourt:
        name: terraform
        user: "{{ ansible_user }}"
      tags: [ 'terraform' ]

    - name: install libreoffice
      package:
        name: libreoffice-fresh
        state: present
      tags: [ 'libreoffice' ]

    - name: Install transmission
      package:
        name: transmission-gtk
        state: present
      tags: [ 'bittorrent' ]

    - name: Install remote desktop software
      package:
        name: gtk-vnc
        state: present
      tags: [ 'vnc' ]

    - name: Install ntfs-3g for mounting ntfs disks
      package:
        name: ntfs-3g
        state: present
      tags: [ 'mount' ]

    - name: Thinkpad battery optimization software TLP
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - tlp
        - tp_smapi
        - acpi_call
        - smartmontools
      tags: [ 'battery' ]

    - name: Enable and start tlp.service
      systemd:
        name: tlp
        daemon_reload: yes
        state: started
        enabled: yes
      tags: [ 'battery' ]

    - name: Enable and start tlp-sleep.service
      systemd:
        name: tlp-sleep
        daemon_reload: yes
        enabled: yes
      tags: [ 'battery' ]

    - name: Disable and stop systemd-rfkill.service
      systemd:
        name: systemd-rfkill
        daemon_reload: yes
        state: stopped
        enabled: no
      tags: [ 'battery' ]
