---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "vars/{{ inventory_hostname }}.yml"
  roles:
    - pkgs
  tasks:

  # mkinitcpio
  - name: Add encrypt to mkinitcpio.conf
    lineinfile:
      dest=/etc/mkinitcpio.conf
      line='HOOKS="base udev autodetect modconf block encrypt filesystems keyboard fsck"'
      state=present
    register: mkinitcpio
    tags:
      - mkinitcpio

  - name: Run mkinitcpio if updated
    command: mkinitcpio -p linux
    when: mkinitcpio.changed 
    tags:
      - mkinitcpio

  # locale
  - name: Add "{{locale_reg}}.{{locale}}" to locale.gen
    lineinfile:
      dest=/etc/locale.gen
      line="{{locale_reg}}.{{locale}} {{locale}}"
      state=present
    register: locale
    tags:
      - locale

  - name: Generate locale
    shell: "{{item}}"
    with_items:
      - locale-gen
      - echo LANG="{{locale_reg}}.{{locale}}" > /etc/locale.conf
      - export LANG="{{locale_reg}}.{{locale}}"
    when: locale.changed 
    tags:
      - locale

  # Time Zone
  - name: Set timezone to {{time_reg}} {{time_zone}}
    file:
      src=/usr/share/zoneinfo/{{time_reg}}/{{time_zone}}
      dest=/etc/localtime
      owner=root
      group=root
      state=link
    tags:
      - timezone

  # Hostname
  - name: Set hostname
    hostname: name={{ inventory_hostname }}
    register: hostname
    tags:
      - hostname

  - name: echo /etc/hostname
    shell: echo "{{ inventory_hostname }}" > /etc/hostname
    when: hostname.changed
    tags:
      - hostname
