---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
  vars_prompt:
    - name: "archlinux_username"
      prompt: "Enter your system username"
      private: no
    - name: "archlinux_user_real_name"
      prompt: "Enter your full real name"
      private: no
    - name: "archlinux_user_email"
      prompt: "Enter your email address"
      private: no
  roles:
    - authorized_keys
    - sudoers
    - git
    - mkinitcpio
    - hostname
    - locale
    - timezone
    - yaourt
    - pkgs
    - vim
    # - slim
    # - i3
  tasks:

#  # Services
#  - name: Enable Slim
#    service: name=slim
#             enabled=yes
#             state=started
#    tags:
#      - service
#
#  - name: Enable ntpdate
#    service: name=ntpdate
#             enabled=yes
#             state=started
#    tags:
#      - service
