---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
#  vars_prompt:
#    - name: "user_password"
#      prompt: "Enter user password"
#      private: yes

  roles:
    # - user
    # - authorized_keys
    # - sudoers
    # - git
    # - mkinitcpio
    - hostname
    - locale
    - timezone
    - yaourt
    # - pkgs
    - vim
    # - slim
    # - i3
  tasks:

#    # this might be a yaourt thing
#    - name: Install snort
#      package:
#        name: "{{ item }}"
#        state: present
#      with_items:
#        - swig
#        - snort
#        - barnyard2
#        - pulledpork
#      tags: [ 'snort' ]
#
#    - name: Configure snort

# Install netsniff-ng
# Configure netsniff-ng
# netsniff-ng.service

# Install bro
# bro-cut netsniff-ng.pcap
