---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
  roles:
    - pkgs
    # - user
    # - authorized_keys
    # - sudoers
    # - git
    # - mkinitcpio
    - hostname
    - locale
    - timezone
    - yaourt
    - vim
    - i3
    # - slim
  tasks:

