---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
  roles:
    - setup
    - verify_base_install
    - yaourt
    - pkgs
    - vim
    # - slim
    # - i3
  tasks:

#  # Services
#  - name: Enable Slim
#    service: name=slim
#             enabled=yes
#             state=started
#    tags:
#      - service
#
#  - name: Enable ntpdate
#    service: name=ntpdate
#             enabled=yes
#             state=started
#    tags:
#      - service
