---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
  roles:
    - pkgs
    # - user
    # - authorized_keys
    # - sudoers
    # - git
    - mkinitcpio
    - hostname
    - locale
    - time
    - yaourt
    - vim
    - i3
    # - slim
    - zsh
    # - openvpn
    # - ruby
    # - chef
    # - python
    # - docker
  tasks:

  - name: Web browser
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - w3m
      - chromium
      - firefox
    tags: [ 'browser' ]
