---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
  vars_prompt:
    - name: "user_password"
      prompt: "Enter user password"
      private: yes

  roles:
    - user
    - authorized_keys
    - sudoers
    - git
    - mkinitcpio
    - hostname
    - locale
    - timezone
    - yaourt
    - pkgs
    - vim
    # - slim
    # - i3
  tasks:

#  # Services
#  - name: Enable Slim
#    service: name=slim
#             enabled=yes
#             state=started
#    tags:
#      - service
#
#  - name: Enable ntpdate
#    service: name=ntpdate
#             enabled=yes
#             state=started
#    tags:
#      - service
