---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
  - "./vars/{{ inventory_hostname }}.yml"
  - "./secrets/{{ inventory_hostname }}.yml"
  roles:
  - yaourt
  - pkgs
  # - user
  # - authorized_keys
  # - sudoers
  - git
  - mkinitcpio
  - hostname
  - locale
  - time
  - vim
  - zsh
  - i3
  # - slim
  - browser
  # - ssh
  - vpn
  # - gpg
  # - ruby
  - chef
  # - python
  # - docker
  # - vagrant
  # - virtualbox
  - conky
  tasks:

  - name: install vagrant
    package:
      name: vagrant
      state: present
    tags: [ 'vagrant' ]

  - name: install virtualbox
    package:
      name: virtualbox
      state: present
    tags: [ 'virtualbox' ]

  - name: install bluejeans from aur
    yaourt:
      name: bluejeans
      user: "{{ ansible_user }}"
    tags: [ 'bluejeans' ]

  - name: install hipchat from aur
    yaourt:
      name: hipchat
      user: "{{ ansible_user }}"
    tags: [ 'hipchat' ]
