---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - "./vars/{{ inventory_hostname }}.yml"
  roles:
    - setup
    - verify_base_install
    - yaourt
    - pkgs
    - vim
    # - slim
    # - i3
  tasks:

#  # Services
#  - name: Enable Slim
#    service: name=slim
#             enabled=yes
#             state=started
#    tags:
#      - service
#
#  - name: Enable ntpdate
#    service: name=ntpdate
#             enabled=yes
#             state=started
#    tags:
#      - service

#  # Yaourt
#  - name: Clone package-query from github
#    git:
#      repo=https://aur.archlinux.org/package-query.git
#      dest=/home/{{ ansible_user }}/package-query
#    register: pkgqry
#
#  - name: install package-query
#    command: makepkg -si
#      chdir=/home/{{ ansible_user}}/package-query
#    when: pkgqry.changed


