---
- name: install vagrant
  package:
    name: vagrant
    state: present
  tags: [ 'vagrant' ]

- name: Check if vagrant plugins are installed
  become: fasle
  shell: "vagrant plugin list | grep {{ item }}"
  ignore_errors: true
  with_items: "{{ vagrant_plugins }}"
  register: plugins_installed
  tags: [ 'vagrant' ]

- name: install vagrant plugins
  command: vagrant plugin install "{{ item }}"
  become: fasle
  with_items: "{{ vagrant_plugins }}"
  when: plugins_installed | failed
  tags: [ 'vagrant' ]
