---
- name: install vagrant
  package:
    name: vagrant
    state: present
  tags: [ 'vagrant' ]

- name: Check if vagrant plugins are installed
  become: false
  ignore_errors: true
  shell: "vagrant plugin list | grep {{ item }}"
  with_items: "{{ vagrant_plugins }}"
  register: plugins_installed
  when: vagrant_plugins is defined
  tags: [ 'vagrant' ]

- name: install vagrant plugins
  become: false
  ignore_errors: true
  command: vagrant plugin install "{{ item }}"
  with_items: "{{ vagrant_plugins }}"
  when:
    - vagrant_plugins is defined
    - plugins_installed | failed
  tags: [ 'vagrant' ]
