---
- name: install conky
  package:
    name: conky
    state: present
  tags: [ 'conky' ]

- name: generate ~/.conkyrc
  template:
    src: conkyrc.j2
    dest: "/home/{{ ansible_user  }}/.conkyrc"
  tags: [ 'conky' ]
