---
vundle:
  - "Gundo"
  - "git.zip"
  - "fugitive.vim"
  - "The-NERD-tree"
  - "EasyMotion"
  - "ack.vim"
  - "http://github.com/gmarik/snipmate.vim.git"
  - "https://github.com/fholgado/minibufexpl.vim.git"
  - "git://git.wincent.com/command-t.git"
  - "https://github.com/pearofducks/ansible-vim.git"
  - "https://github.com/davidhalter/jedi-vim.git"
  - "https://github.com/nvie/vim-flake8.git"
  - "https://github.com/powerline/powerline.git"
  - "https://github.com/ngmy/vim-rubocop.git"
  - "https://github.com/tpope/vim-surround.git"
  - "MarcWeber/vim-addon-mw-utils"
  - "tomtom/tlib_vim"
  - "garbas/vim-snipmate"
  - "vadv/vim-chef"
set: 
  - laststatus=2
  - showtabline=2
  - noshowmode
  - foldmethod=indent
  - foldlevel=99
  - background=dark
  - completeopt=menuone,longest,preview
  - colorcolumn=81
  - cursorcolumn
  - cursorline
  - expandtab
  - tabstop=2
  - shiftwidth=2
  - spell
  - spelllang=en
  - spellfile=$HOME/.vim/en.utf-8.add
  - number

map:
  - <c-j> <c-w>j
  - <c-k> <c-w>k
  - <c-l> <c-w>l
  - <c-h> <c-w>h
  - <leader>td <Plug>TaskLisk
  - "<leader>g :GundoToggle<CR>"
  - "<F2> :NERDTreeToggle<CR>"

syntax:
  - "on"

colorscheme: 
  - slate

filetype:
  - "on"
  - plugin indent on

let:
  - g:pyflakes_use_quickfix = 0

command:
  - Fuckyou w !sudo tee %

autocmd:
  - FileType ruby,eruby set filetype=ruby.eruby.chef
