---
- name: install openssh
  package:
    name: openssh
    state: present
  tags: [ 'ssh' ]

- name: ensure ~/.config/systemd
  file:
    path: "/home/{{ ansible_user }}/.config/systemd/user"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags: [ 'ssh' ]

- name: generate ssh-agent.service
  template:
    src: ssh-agent.service.j2
    dest: "/home/{{ ansible_user }}/.config/systemd/user/ssh-agent.service"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  tags: [ 'ssh' ]

#  notify:
#    - restart ssh-agent
#
#handlers:

  # - name: start and enable ssh-agent
