---
- name: install zsh and dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - zsh
  tags: [ 'zsh' ]

- name: use oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "/home/{{ user.name }}/.oh-my-zsh"
    version: master
  tags: [ 'zsh' ]

- name: create ~/.z/ dir
  file:
    path: "/home/{{ user.name }}/.z"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ "zsh" ]

- name: generate ~/.z/ files
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ user.name }}/.z/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  with_items:
    - zshrc
    - zshenv
    - alias.zsh
    - export.zsh
    - functions.zsh
    - keybindings.zsh
    - chef.zsh
    - aws.zsh
    - python.zsh
    - ansible.zsh
  tags: [ 'zsh' ]

- name: link the zshrc and zshenv
  file:
    src: "/home/{{ user.name }}/.z/{{ item }}"
    dest: "/home/{{ user.name }}/.{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: link
    force: yes
  with_items:
    - zshrc
    - zshenv
  tags: [ 'zsh' ]

- name: change shell from bash to zsh
  user:
    name: "{{ user.name }}"
    shell: /bin/zsh
  tags: [ 'zsh' ]
