---
- name: Install chef-dk
  yaourt:
    name: chef-dk
    user: "{{ ansible_user }}"
  tags: [ 'chef' ]

- name: link /usr/bin/inspec
  file:
    src: /opt/chefdk/bin/inspec
    dest: /usr/bin/inspec
    owner: root
    group: root
    state: link
  tags: [ 'chef' ]

- name: Ensure ~/workspace dir exists
  file:
    dest: "/home/{{ ansible_user }}/workspace"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags: [ 'chef' ]

- name: Clone chef {{ chef.repo }}
  become: fasle
  git:
    repo: "{{ chef.repo_url }}"
    dest: "/home/{{ ansible_user }}/workspace/{{ chef.repo }}"
    accept_hostkey: true
  when: chef.repo is defined
  tags: [ 'chef' ]

- name: copy validation key
  become: false
  copy:
    src: "{{ chef.validation_key_file }}"
    dest: "{{ chef.validation_key_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0400
  when: chef.validation_key_file is defined
  tags: [ 'chef' ]

- name: Clone chef cookbooks
  become: fasle
  git:
    repo: "{{ chef.cookbook_url }}{{ item }}.git"
    dest: "/home/{{ ansible_user }}/workspace/{{ chef.repo }}/cookbooks/{{ item }}"
    accept_hostkey: true
  when: chef.cookbooks is defined
  with_items: "{{ chef.cookbooks }}"
  tags: [ 'chef' ]

- name: Ensure ~/.berkshelf dir exists
  file:
    dest: "/home/{{ ansible_user }}/.berkshelf"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags: [ 'chef' ]

- name: Generate ~/.berkshelf/config.json
  template:
    src: config.json.j2
    dest: "/home/{{ ansible_user }}/.berkshelf/config.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  when: chef.server_url is defined
  tags: [ 'chef' ]
