---
- name: Install chef-dk
  yay:
    name: chef-dk
    user: "{{ user.name }}"
  tags: [ 'chef' ]

- name: Install chef extras
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - graphviz
  tags: [ 'chef' ]

- name: link /usr/bin/inspec
  file:
    src: /opt/chefdk/bin/inspec
    dest: /usr/bin/inspec
    owner: root
    group: root
    state: link
  tags: [ 'chef' ]

- name: Ensure ~/workspace dir exists
  file:
    dest: "/home/{{ user.name }}/workspace"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'chef' ]

- name: Clone chef {{ chef.repo }}
  become: false
  git:
    repo: "{{ chef.repo_url }}"
    dest: "/home/{{ user.name }}/workspace/{{ chef.repo }}"
    version: master
    accept_hostkey: true
  when: chef.repo is defined
  tags: [ 'chef' ]

- name: copy validation key
  become: false
  copy:
    src: "{{ chef.validation_key_file }}"
    dest: "{{ chef.validation_key_path }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0400
  when: chef.validation_key_file is defined
  tags: [ 'chef' ]

- name: Ensure ~/.berkshelf dir exists
  file:
    dest: "/home/{{ user.name }}/.berkshelf"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'chef' ]

- name: Generate ~/.berkshelf/config.json
  template:
    src: config.json.j2
    dest: "/home/{{ user.name }}/.berkshelf/config.json"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0644
  when: chef.server_url is defined
  tags: [ 'chef' ]
