---
- name: Install chef-dk
  yaourt:
    name: chef-dk
    user: "{{ ansible_user }}"
  tags: [ 'chef' ]

- name: Install chef extras
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - graphviz
  tags: [ 'chef' ]

- name: link /usr/bin/inspec
  file:
    src: /opt/chefdk/bin/inspec
    dest: /usr/bin/inspec
    owner: root
    group: root
    state: link
  tags: [ 'chef' ]

- name: Ensure ~/workspace dir exists
  file:
    dest: "/home/{{ ansible_user }}/workspace"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags: [ 'chef' ]

- name: Clone chef {{ chef.repo }}
  become: false
  git:
    repo: "{{ chef.repo_url }}"
    dest: "/home/{{ ansible_user }}/workspace/{{ chef.repo }}"
    version: master
    accept_hostkey: true
  when: chef.repo is defined
  tags: [ 'chef' ]

- name: copy validation key
  become: false
  copy:
    src: "{{ chef.validation_key_file }}"
    dest: "{{ chef.validation_key_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0400
  when: chef.validation_key_file is defined
  tags: [ 'chef' ]

- name: Clone chef cookbooks
  become: false
  git:
    repo: "{{ chef.cookbook_url }}{{ item }}.git"
    dest: "/home/{{ ansible_user }}/workspace/{{ chef.repo }}/cookbooks/{{ item }}"
    version: master
    accept_hostkey: true
  with_items: "{{ chef.cookbooks }}"
  when: chef.cookbooks is defined
  tags:
    - chef
    - cookbooks

- name: Generate .rubocop.yml in each cookbook
  become: false
  template:
    src: rubocop.yml.j2
    dest: "/home/{{ ansible_user }}/workspace/{{ chef.repo }}/cookbooks/{{ item }}/.rubocop.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  with_items: "{{ chef.cookbooks }}"
  when: chef.cookbooks is defined
  tags:
    - chef
    - rubocop

#- name: Generate .rubocop_todo.yml in each cookbook
#  become: false
#  when: chef.cookbooks is defined
#  tags:
#    - chef
#    - rubocop

- name: Ensure ~/.berkshelf dir exists
  file:
    dest: "/home/{{ ansible_user }}/.berkshelf"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags: [ 'chef' ]

- name: Generate ~/.berkshelf/config.json
  template:
    src: config.json.j2
    dest: "/home/{{ ansible_user }}/.berkshelf/config.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  when: chef.server_url is defined
  tags: [ 'chef' ]
