---
- name: Install x server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
  tags: [ 'i3' ]

- name: Install video driver
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mesa
    - xf86-video-vesa
    - xf86-video-nouveau
  tags: [ 'i3' ]

- name: Install i3
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - i3-wm
    - i3lock
    - i3status
  tags: [ 'i3' ]

- name: Install i3 extras
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - conky
    - dmenu
    - dunst
    - feh
    - redshift
    - rxvt-unicode
    - scrot
    - ttf-dejavu
    - udiskie
    - xf86-input-synaptics
    - xorg-xmodmap
    - xorg-xrdb
    - urxvt-perls
  tags: [ 'i3' ]

- name: install xcalib from aur
  yay:
    name: xcalib
    user: "{{ user.name }}"
  tags: [ 'i3' ]

- name: Create ~/.i3 directories
  file:
    path: "/home/{{ user.name }}/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  with_items:
    - .i3
    - .i3/bin
    - .i3/systemd
  tags: [ 'i3' ]

- name: generate i3 config files
  template:
    src: "i3/{{ item }}.j2"
    dest: "/home/{{ user.name }}/.i3/{{ item }}"
  with_items:
    - Xresources.dark
    - Xresources.light
    - config
    - conkyrc
    - dark.xresources
    - dunstrc
    - gtk-3.0-settings
    - gtkrc-2.0
    - light.xresources
    - xinitrc
    - xmodmap
    - xresources
  tags: [ 'i3' ]

- name: generate i3 bin files
  template:
    src: "i3/{{ item }}.j2"
    dest: "/home/{{ user.name }}/.i3/{{ item }}"
    mode: 0777
  with_items:
    - bin/apply-colors-runtime
    - bin/conky-wrapper
  tags: [ 'i3' ]

- name: symlink xinitrc
  file:
    src: "/home/{{ user.name }}/.i3/xinitrc"
    dest: "/home/{{ user.name }}/.xinitrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: link
  tags: [ 'i3' ]

- name: create $HOME/.urxvt/ext/ dir
  file:
    path: "/home/{{ user.name }}/.urxvt/ext/"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'i3' ]

- name: download urxvt font-size plugin
  get_url:
    url: https://raw.githubusercontent.com/majutsushi/urxvt-font-size/master/font-size
    dest: "/home/{{ user.name }}/.urxvt/ext/font-size"
    mode: 0755
  tags: [ 'i3' ]

- name: enable urxvt keyboard-select plugin
  file:
    src: /usr/lib/urxvt/perl/keyboard-select
    dest: "/home/{{ user.name }}/.urxvt/ext/keyboard-select"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: link
  tags: [ 'i3' ]

- name: enable urxvt url-select plugin
  file:
    src: /usr/lib/urxvt/perl/url-select
    dest: "/home/{{ user.name }}/.urxvt/ext/url-select"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: link
  tags: [ 'i3' ]

- name: create $HOME/screenshots dir for scrot
  file:
    path: "/home/{{ user.name }}/screenshots/"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'i3' ]
