---
- name: Install x server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
  tags: [ 'i3' ]

- name: Install video driver
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mesa
    - xf86-video-vesa
    - xf86-video-nouveau
  tags: [ 'i3' ]

- name: Install i3
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - i3-wm
    - i3lock
    - i3status
  tags: [ 'i3' ]

- name: Install i3 extras
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - dmenu
    - dunst
    - rxvt-unicode
    - ttf-dejavu
    - conky
    - xf86-input-synaptics
    - scrot
    - xorg-xmodmap
    - xorg-xrdb
    - redshift
  tags: [ 'i3' ]

- name: install xcalib from aur
  yaourt:
    name: xcalib
    user: "{{ ansible_user }}"
  tags: [ 'i3' ]

- name: Create ~/.i3 directories
  file: 
    path: "/home/{{ ansible_user }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - .i3
    - .i3/bin
    - .i3/systemd
  tags: [ 'i3' ]

- name: generate i3 config files
  template:
    src: "i3/{{ item }}.j2"
    dest: "/home/{{ ansible_user }}/.i3/{{ item }}"
  with_items:
    - Xresources.dark
    - Xresources.light
    - config
    - conkyrc
    - dark.xresources
    - dunstrc
    - gtk-3.0-settings
    - gtkrc-2.0
    - light.xresources
    - xinitrc
    - xmodmap
    - xresources
  tags: [ 'i3' ]

- name: generate i3 bin files
  template:
    src: "i3/{{ item }}.j2"
    dest: "/home/{{ ansible_user }}/.i3/{{ item }}"
    mode: 0777
  with_items:
    - bin/apply-colors-runtime
    - bin/conky-wrapper
  tags: [ 'i3' ]

- name: symlink xinitrc
  file:
    src: "/home/{{ ansible_user }}/.i3/xinitrc"
    dest: "/home/{{ ansible_user }}/.xinitrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  tags: [ 'i3' ]
