---
- name: Install git
  package: name=git
  become: yes

- name: Check if git name is set
  shell: git config user.name
  register: git_name
  tags: [ "git" ]
  become: yes
  become_user: "{{ user.name }}"

- name: Configure git name
  command: "/usr/bin/git config --global user.name \"{{ user.real_name }}\""
  become: yes
  become_user: "{{ user.name }}"
  when: git_name.stdout != "{{ user.real_name }}"
  tags: [ "git" ]

- name: Check if git email is set
  shell: git config user.email
  register: git_email
  tags: [ "git" ]
  become: yes
  become_user: "{{ user.name }}"

- name: configure git email
  command: "/usr/bin/git config --global user.email \"{{ user.email }}\""
  become: yes
  become_user: "{{ user.name }}"
  when: git_email.stdout != "{{ user.email }}"
  tags: [ "git" ]
