---
- name: install openvpn
  package:
    name: openvpn
    state: present
  tags: [ 'vpn' ]

# maybe add more later
# https://galaxy.ansible.com/kbrebanov/openvpn/

- name: start openvpn-client@.service
  systemd:
    name: "openvpn-client@{{ item }}"
    daemon_reload: yes
    state: started
    enabled: yes
  with_items: "{{ vpn.clients }}"
  when: vpn.clients is defined
  tags: [ "vpn" ]
