---
- name: install web browsers
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox
    - w3m
    - chromium
  tags: [ 'browser' ]

- name: install pepper-flash from aur
  yay:
    name: pepper-flash
    user: "{{ ansible_user }}"
  tags: [ 'browser' ]

# Firefox
- name: install firefox extras
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox-noscript
    - flashplugin
    # - vmware-vsphere-web-client-plugin
  tags: [ 'browser' ]

# - name: install firefox extras from aur
#   yay:
#     name: "{{ item }}"
#     user: "{{ ansible_user }}"
#   with_items:
#     # - lastpass
#     - ttf-ms-fonts
#     - vimperator
#   tags: [ 'browser' ]
