---
- name: install web browsers
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox
    - w3m
    - chromium
  tags: [ 'browser' ]

- name: install pepper-flash from aur
  yay:
    name: pepper-flash
    user: "{{ user.name }}"
  tags: [ 'browser' ]

# Firefox
- name: install firefox extras
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox-noscript
    - flashplugin
    # - vmware-vsphere-web-client-plugin
  tags: [ 'browser' ]

- name: install firefox extras from aur
  yay:
    name: lastpass
    user: "{{ user.name }}"
  with_items:
    - lastpass
    - ttf-ms-fonts
    - vimperator
  tags: [ 'browser' ]
