---

- name: install virtualbox
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox-host-modules-arch
    - virtualbox
  notify:
   - vboxreload
  tags: [ 'virtualbox' ]
