---

- name: Install ansible-lint
  yay:
    name: ansible-lint
    user: "{{ user.name }}"
  tags: [ 'ansible' ]

- name: Install sshpass
  package:
    name: sshpass
    state: present
  tags: [ 'ansible' ]

# pysphere
