---
- name: Install pianobar
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libao
    - ffmpeg
    - readline
    - json-c
    - libgcrypt
    - pianobar
  tags: [ 'pianobar' ]

- name: create config dir
  file:
    path: "/home/{{ user.name }}/.config/pianobar"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ 'pianobar' ]

- name: generate pianobar config
  template:
    src: config.j2
    dest: "/home/{{ user.name }}/.config/pianobar/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  tags: [ 'pianobar' ]
