---
- name: Install vim
  package:
    name: vim
    state: present
  tags: [ "vim" ]

- name: create ~/.vim diretory
  file:
    path: "/home/{{ user.name }}/.vim/"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags: [ "vim" ]

- name: Clone vundle from github
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{ user.name }}/.vim/bundle/Vundle.vim"
    version: master
  tags: [ "vim" ]

- name: Generate ~/.vimrc
  template:
    src: vimrc.j2
    dest: "/home/{{ user.name }}/.vimrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0644"
  notify: install plugins
  tags: [ "vim" ]

- name: Touch spell-check file
  file:
    path: "/home/{{ user.name }}/.vim/en.utf-8.add"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: touch
    mode: 0644
  tags: [ "vim" ]

- name: vim info
  debug:
    msg: "See ':h vundle' for more details."
  tags: [ "vim" ]
