---
- name: Install alsa-utils
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - alsa-utils
    - alsa-oss
    - alsa-plugins
  tags: [ 'sound' ]

- name: Install PulseAudio
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
  notify: restart pulse as user
  tags: [ 'sound' ]

- name: Switch output to newly connected devices
  lineinfile:
    line: "load-module module-switch-on-connect"
    dest: /etc/pulse/default.pa
    state: present
  tags: [ 'sound' ]

#- name: Install pasystray
#  yaourt:
#    name: pasystray-gtk3-standalone
#    user: "{{ ansible_user }}"
#  tags: [ 'sound' ]

- name: Install pulseaudio-ctl
  yaourt:
    name: pulseaudio-ctl
    user: "{{ ansible_user }}"
  tags: [ 'sound' ]

- name: Generate /etc/libao.conf
  template:
    src: libao.conf.j2
    dest: /etc/libao.conf
  notify: restart pulse as user
  tags: [ 'sound' ]

#I figured it out myself. here is how you do it for anyone who has these issues too and cant find any answers
#Sound with Pulse and ALSA
##sudo pacman -S alsa-utils
##sudo pacman -S alsa-oss
##sudo pacman -S alsa-plugins
##sudo pacman -S pulseaudio
##sudo pacman -S pavucontrol
##sudo pacman -S ib32-alsa-plugins
##sudo pacman -S lib32-libpulse
##sudo pacman -S pulseaudio-alsa
#Setting up Sound
## groupadd pulse-access
## groupadd pulse-rt
##gpasswd -a "yourusername" pulse-access
##gpasswd -a "yourusername" pulse-rt
##sudo nano /etc/asound.conf
##pcm.pulse {
#    type pulse
#}
#ctl.pulse {
#    type pulse
#}
#pcm.!default {
#    type pulse
#}
#ctl.!default {
#    type pulse
#}
#sudo nano /etc/libao.conf
##default_driver=pulse
#
#
#once you finish doing all that, load up your pavucontrol, and switch it to the device you want sound from (if in the internet browser, play a video first for it to show up)
